AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Week 1 - Lambda Basics

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256

Resources:
  StartSimulationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      CodeUri: .
      Environment:
        Variables:
          SESSION_KEY: "9662"
      Policies:
        - AWSLambdaBasicExecutionRole
